name: Run Checks

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    run-checks:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v4

            - name: Use Node.js 18
              uses: actions/setup-node@v4
              with:
                  node-version: "18"
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build React project
              run: pnpm run build

            - name: Run linter
              run: pnpm run lint
